version: "3"
services:
  postgres:
    image: "postgres:9"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"
    networks:
      - testnetwork
    environment:
      NODE_ENV:
  hotel-booking:
    image: teststack/hotel-booking
    # env_file:
    #   - ./.env
    depends_on:
      - "postgres"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.3"
          memory: 250M
      restart_policy:
        condition: on-failure
    ports:
      - "8080:8080"
    networks:
      - testnetwork
    environment:
      NODE_ENV:
networks:
  testnetwork:
volumes:
  postgres-data:
    external:
      name: postgres-data
