version: "3"
services:
  postgres:
    image: "teststack/postgres"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "5432:5432"
    networks:
      - testnetwork
    environment:
      - "DB_USER=admin"
      - "DB_PASSWORD=123"
      - "DB_DATABASE=test"
      - "POSTGRES_PASSWORD=123"
networks:
  testnetwork:
volumes:
  postgres-data:
    external:
      name: postgres-data
